import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import AppBreadcrumb from "@/components/app-breadcrumb";

const poppinSans = Poppins({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Admin Bicara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinSans.className} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full p-5">
            <div className="flex flex-row items-center gap-4 justify-between">
              <SidebarTrigger />
              <AppBreadcrumb />
            </div>
            <div className="pt-3 w-full">
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
